export const viteWatchIgnored = [
  "**/src-tauri/**",
  "**/.learnings/**",
  "**/.gemini/**",
  "**/tmp/**",
  "**/.tmp/**",
  "**/.wardian/**",
  "**/state.db",
  "**/state.db-*",
  "**/agents/*/habitat/**",
  "**/agents/*/claude/**",
  "**/agents/*/.codex/**",
  "**/agents/*/.claude/**",
  "**/agents/*/.opencode/**",
] as const;
